from BaseTyping import *
from main import Application, SQLDatabase
import tkinter

class ImageHolderUpdater:
    errorImage = None # type: Optional[ImageTk]
    def Image(self) -> str:...
    def Image(self, newimage: Optional[str]) -> None:...
    def __init__(self, Label: tkinter.Label, Image: str = ""):...
    def set(self, data:str) -> None:...



class MyBarcodePage(tkinter.Frame):
    def SwitchTo(self) -> None:...
    def set_info(self, infoTuple: Optional[Tuple[str]]) -> None:...
    def queryAndSelect(self, event: tkinter.Event) -> Tuple[bool,str]:...
    def queryDataBase(self, barcode: str) -> bool:...
    @staticmethod
    def selectAll(event: tkinter.Event) -> None:...
    @staticmethod
    def containsId(infoTuple: Tuple[str]) -> bool:...
    def __init__(self, parent: tkinter.Frame, database: SQLDatabase, MainApp: Application):...

    courier = {} # type: Dict[str, Union[Tuple, str]]
    queryDescriptor = {} # type: Dict[str, Union[Tuple, str]]
    queryData = {} # type: Dict[str, Union[Tuple, str]]
    padStick = {} # type: Dict[str, Union[Tuple, str]]
    superSticky = {} # type: Dict[str, Union[Tuple, str]]

class EmptyVar:
    def set(self, item:Optional[str]) -> None:...