from typing import *
import tkinter
import sqlite3
import main
import tkinter.ttk as ttk

class Application:
    SpecialBarcodes = {} # type: Dict[str, str]
    def checkSpecialBarcodes(self, text:str) -> bool:...
    def destroySelf(self, *args) -> None:...
    def __init__(self, fullscreen:bool = False):...
    def chooseNoteBookTarget(self, event: tkinter.Event) -> None:...

