from main import *
from sqldatabase import *

class QueryPage(MyBarcodePage):
    def set_info(self, infoTuple: Optional[Tuple[str]]):...
    def SwitchTo(self) -> None:...
    def __init__(self, parent: tkinter.Frame, database: SQLDatabase, MainApp: Application):...

